_wandb:
    value:
        cli_version: 0.23.1
        e:
            k1ouxcxxhcwksblgn6ktvdov6aobyldi:
                codePath: train_od_fct.py
                codePathLocal: train_od_fct.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "906365308928"
                        used: "364175745024"
                email: une_glace@sjtu.edu.cn
                executable: E:\software\Anaconda3\Anaconda_envs\envs\dip\python.exe
                git:
                    commit: afd5f8c4ba54c36e6caafc832e13748a81ad7a3f
                    remote: https://github.com/une-glace/AU3605_FinalPro.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-7f38f7e5-86e5-a9d3-750f-cdc8beb46308
                host: DESKTOP-9S02SEE
                memory:
                    total: "16505966592"
                os: Windows-10-10.0.19045-SP0
                program: E:\sync\courses\AU3605\FinalPro\DIPfp\train_od_fct.py
                python: CPython 3.10.19
                root: E:\sync\courses\AU3605\FinalPro\DIPfp
                startedAt: "2025-12-19T14:07:42.724537Z"
                writerId: k1ouxcxxhcwksblgn6ktvdov6aobyldi
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 8
learning_rate:
    value: 0.0001
num_epochs:
    value: 100
train_size:
    value: 330
val_size:
    value: 83
